[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "expensetracker"

[services.env]
NODE_ENV = "production"
NEXTAUTH_URL = "${{RAILWAY_STATIC_URL}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
DATABASE_URL = "${{DATABASE_URL}}"

[services.healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3