[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run db:deploy && npm run db:seed-production && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "expensetracker"

[services.env]
NODE_ENV = "production"
NEXTAUTH_URL = "${{RAILWAY_STATIC_URL}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
DATABASE_URL = "${{DATABASE_URL}}"

[services.healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3

# PostgreSQL service configuration
[[services]]
name = "postgres"
source = "postgres"

[services.variables]
POSTGRES_DB = "expensetracker"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "${{POSTGRES_PASSWORD}}"